import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

let outdir = "./";
const outdirArgIdx = process.argv.findIndex(arg => arg === '--outdir' || arg.startsWith('--outdir='));
if (outdirArgIdx !== -1) {
  const arg = process.argv[outdirArgIdx];
  if (arg.startsWith('--outdir=')) {
    outdir = arg.split('=')[1];
  } else if (outdirArgIdx + 1 < process.argv.length) {
    outdir = process.argv[outdirArgIdx + 1];
  }
}

const copyManifestAndStyles = () => {
  if (outdir !== "./") {
    try {
      fs.mkdirSync(outdir, { recursive: true });
      fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
      if (fs.existsSync("styles.css")) {
        fs.copyFileSync("styles.css", path.join(outdir, "styles.css"));
      }
    } catch (e) {
      console.error("Failed to copy manifest/styles to outdir:", e);
    }
  }
};

const copyPlugin = {
  name: 'copy-files',
  setup(build) {
    build.onEnd(() => {
      copyManifestAndStyles();
      console.log("Built successfully and copied manifest/styles to " + outdir);
    });
  }
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/state',
		'@codemirror/view',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/autocomplete',
		'@codemirror/commands',
	],
	format: 'cjs',
	target: 'es2022',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(outdir, 'main.js'),
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
